version: "3.8"

services:
  app:
    build: .
    container_name: keygen_app
    depends_on:
      - vault
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - ATT52135.env
    restart: always

  vault:
    image: vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
